### ISSUE TITLE
[Discussion][Issue] Fix Bottom Omnibox

### ISSUE THREAD

**Issue by Thunderbottom** [balzathor/UltimateBrowserProject#65] opened 2015-11-22 17:57 UTC
So Keyboard is shown above the bottom omnibox while typing, so it gets hidden behind the keyboard.

While scrolling, bottom omnibox hides (While scrolling top, should be reversed) and shows "about:blank: for a brief period like some Milliseconds when it starts hiding.

Overall, the omnibox has choppy animations, need to fix that too.

**Comment by xdevs23** [comment] 2015-11-22 19:10
Yes, I saw that. Need to move it up when keyboard is shown. 
Also I think we should remove that "about:blank" thing and we should init the webview when the application starts, because when no tabs are open the webview doesn't exist, only after typing in an url and the previous sessions hasnt been restored.
There are no animations on the omnibox. We have to create one to animate fade in/out like in chrome.

But it's not bad, is it?

**Comment by Thunderbottom** [comment] 2015-11-23 04:33
It's not bad.

**Comment by xdevs23** [comment] 2015-11-23 06:12
Don't worry everything has a solution.

**Comment by Thunderbottom** [comment] 2015-11-30 16:35
Have you tried fixing this issue? We need to release a version soon, cause I'll be having a lot lesser time in December due to work and stuff.

**Comment by xdevs23** [comment] 2015-11-30 17:51
Oh sorry, I didn't fix it, yet, I am currently very busy and also not working in the environment, which I use for android development, but in the next days I would have time to do it.

**Comment by Thunderbottom** [comment] 2015-12-01 10:35
Alright, take your time.

**Comment by xdevs23** [comment] 2015-12-09 17:14
See https://github.com/Thunderbottom/UltimateBrowserProject/commit/c447c5d8d3b89f9b299a1bd5195da006877c3e2b

Just need to fix keyboard

**Comment by Thunderbottom** [comment] 2015-12-10 17:23
@xdevs23 some bugs that I found in the latest build-
- If you install the app for the first time, this screen is shown - `Cannot Load URL`
  ![bug1](https://cloud.githubusercontent.com/assets/11243138/11722766/a16ea6b4-9f90-11e5-8cc1-b79053700c5f.png)
- Then when you click OK, this screen is shown- 

![screenshot_2015-12-10-15-25-54](https://cloud.githubusercontent.com/assets/11243138/11722778/b7227dc8-9f90-11e5-8dbe-9a2d2acc602c.png)

**Comment by xdevs23** [comment] 2015-12-10 17:37
Allright, will take a look.

**Comment by xdevs23** [comment] 2015-12-11 06:42
Could you tell me the URL which is being loaded?

**Comment by Thunderbottom** [comment] 2015-12-11 07:04
Asset file

**Comment by xdevs23** [comment] 2015-12-11 11:58
Yea but is the URL correct?

**Comment by xdevs23** [comment] 2015-12-11 12:16
Ok, the URL is correct, the issue seems to be that the webview doesn't get initialized correctly at first start-up. If you open a new tab, you can switch back to the first thread and it works.

Try creating a new tab or swipe the omnibox to left/right and it should initialize the webview:
![screenshot_2015-12-11-13-14-50](https://cloud.githubusercontent.com/assets/6959245/11743651/7bc90aca-a009-11e5-92b4-ef606fb3c7f8.png)

**Comment by Thunderbottom** [comment] 2015-12-11 13:35
Is it because of [this](https://github.com/Thunderbottom/UltimateBrowserProject/blob/master/app/src/main/java/io/github/UltimateBrowserProject/Activity/BrowserActivity.java#L238)

**Comment by xdevs23** [comment] 2015-12-11 13:43
Ok I will see how to fix it

But we should leave that line untouched.

**Comment by xdevs23** [comment] 2015-12-11 17:59
I already played around, but I'm not able to fix it properly. I don't really know how to handle that complex and mixed up layout.

The problem is that the first launch is not implemented correctly.

We should remove nearly everything that has to do with the first startup and just let it load the introduction URL on first startup.

I will take a look on that later, I think tomorrow.

**Comment by xdevs23** [comment] 2015-12-11 18:03
I think it is more because of [this](https://github.com/Thunderbottom/UltimateBrowserProject/blob/master/app/src/main/java/io/github/UltimateBrowserProject/Activity/BrowserActivity.java#L286) and [that](https://github.com/Thunderbottom/UltimateBrowserProject/blob/master/app/src/main/java/io/github/UltimateBrowserProject/Activity/BrowserActivity.java#L1010) and also [that](https://github.com/Thunderbottom/UltimateBrowserProject/blob/master/app/src/main/java/io/github/UltimateBrowserProject/Activity/BrowserActivity.java#L1151)

**Comment by xdevs23** [comment] 2015-12-12 10:46
@Thunderbottom Fixed the first launch! :grinning:

**Comment by Thunderbottom** [comment] 2015-12-13 03:58
Nice, man. I just tested and saw that the omnibox tinting sometimes turns the omnibox transparent, and we need to fix bottom layout for when keyboard is used.

**Comment by xdevs23** [comment] 2015-12-13 08:10
Yes, I saw that, too.

For keyboard I have a good idea, we can use onMeasure() to move the omnibox up when needed. There's no event for software keyboard so we have to use that

**Comment by xdevs23** [comment] 2015-12-13 08:13
But there's another bug... When restoring tabs from last session, the wrong site is loaded. It doesn't load the **last** page that was open before closing UBP, it loads the page **before the last** or a random one.

After that all is fixed, we can release a new version, can't we?

**Comment by Thunderbottom** [comment] 2015-12-13 08:28
Well, restoring website was fine. I'll take a look at it

**Comment by xdevs23** [comment] 2015-12-13 08:30
Yes, I am having the problem that it loads the wrong page. If I was on 5 pages, it loads the 4th but sometimes a random one...
I think we need to improve the way the pages are saved.

**Comment by xdevs23** [comment] 2015-12-13 14:54
Now it's fixed :D

**Closed as completed by xdevs23** 2015-12-13 14:54 UTC

**Comment by Thunderbottom** [comment] 2015-12-16 14:44
Bug? This happens every time. It happened since I installed it. 
![screenshot_2015-12-16-09-52-50](https://cloud.githubusercontent.com/assets/11243138/11843812/97f268e6-a431-11e5-9cd6-a00455b6bee9.png)

**Comment by xdevs23** [comment] 2015-12-16 14:51
Doesn't happen to me, I tested on Marshmallow, KitKat and Jelly Bean. On physical and emulated devices.

**Comment by Thunderbottom** [comment] 2015-12-16 17:36
Send an apk quick so I'll test on the go on some devices

**Comment by xdevs23** [comment] 2015-12-16 17:50
Just rename it to UBPCustom.apk and there you go!
[UBPCustom.zip](https://github.com/Thunderbottom/UltimateBrowserProject/files/64326/UBPCustom.zip)

Eventually deleting app data would help...
