### ISSUE TITLE
Weird Bug pls help

### ISSUE THREAD

**Issue by Thunderbottom** [balzathor/UltimateBrowserProject#53] opened 2015-11-09 10:47 UTC
Well, so now, the top part of the page is not shown in the view until I zoom in.

Here's the unzoomed page -

![Unzoomed](https://cloud.githubusercontent.com/assets/11243138/11031816/1cec1576-86fd-11e5-8764-3c5394a035ed.png)

And here's the page zoomed in -

![zoom](https://cloud.githubusercontent.com/assets/11243138/11031823/2cbfbbd8-86fd-11e5-9200-46bf747d21ec.png)

As you can see the top part of the page is not shown in the unzoomed view, and I haven't touched anything in the WebView. @takahirom @james9909 pls help ;-;

**Comment by Thunderbottom** [comment] 2015-11-10 02:05
@takahirom pls help

**Comment by takahirom** [comment] 2015-11-10 03:42
I want to help you.
But, I'm so busy..
Probably I can look this in weekend.

**Comment by Thunderbottom** [comment] 2015-11-10 09:18
okay thanks :)

**Comment by xdevs23** [comment] 2015-11-11 19:06
Will also look into it

**Comment by xdevs23** [comment] 2015-11-12 14:58
Seems to work now... after my commits
![screenshot_2015-11-12-15-49-53](https://cloud.githubusercontent.com/assets/6959245/11121426/1c05f662-8956-11e5-9880-8f77186b5def.png)

I have generated an apk from latest source code (including my latest commits today) and it is working.
All times prior that apk did also have the bug.

Seems that the missing german arrays.xml was causing it, after adding it, it is working.

EDIT:

Ok, I checked it out again, and somehow the bug persists.

EDIT 2:

@balzathor found what is causing it: the webview has to be moved under the omnibox because it is overlapping the webview, or when using bottom, the status bar overlaps it.
I will try to fix it, already playing around.
Not overlapping:
![screenshot_2015-11-12-16-46-17](https://cloud.githubusercontent.com/assets/6959245/11122873/6159c58e-895d-11e5-8434-2a38554c901b.png)
Overlapping:
![screenshot_2015-11-12-16-46-24](https://cloud.githubusercontent.com/assets/6959245/11122872/61570d94-895d-11e5-9811-59720c66b233.png)

To reproduce this, set the omnibox position to top and scroll down a bit the page.
After scrolling down, scroll back to the top but without letting the omnibox appear again.

**Comment by Thunderbottom** [comment] 2015-11-12 16:08
But the top positioned omnibox also wasn't meant to overlap some portion, I don't know why but this is happening since last release, need to check past commits

**Comment by xdevs23** [comment] 2015-11-12 16:18
I found it!

It is in UltimateBrowserProjectWebView.java on "initWebView" where you define the OnTouchListener.

I tried this:

``` java
               if (action == MotionEvent.ACTION_DOWN) {
                    y2 = y1;
                } else if (action == MotionEvent.ACTION_UP) {
                    if ((y1 - y2) > UP_SCROLL_THRESHOLD) {
                        browserController.showOmnibox();
                        int l = view.getLeft(), t = view.getTop() + 48,
                            b = view.getBottom(), r = view.getRight();
                        view.layout(l, t, r, b);
                    } else if ((y1 - y2) < -DOWN_SCROLL_THRESHOLD) {
                        browserController.hideOmnibox();
                        int l = view.getLeft(), t = view.getTop() - 48,
                            b = view.getBottom(), r = view.getRight();
                        view.layout(l, t, r, b);
                    }
                    y2 = 0;
                }
```

And it works in some way...
It is buggy, but if you overscroll 2 times after reaching the top of the page, it doesn't overlap anymore.

I will commit now and you just have to improve my solution...

But don't forget to do that in initWebView also, so that it is immediately correct.

![screenshot_2015-11-12-17-15-37](https://cloud.githubusercontent.com/assets/6959245/11123690/664b8ae2-8961-11e5-812a-9d084c9df606.png)

**Comment by xdevs23** [comment] 2015-11-12 16:25
See https://github.com/balzathor/UltimateBrowserProject/commit/f2fd65b9f8a253dc4d640948d8a1afb8495ed8ae

**Comment by Thunderbottom** [comment] 2015-11-12 16:39
The bug is, if you drag it more downwards, the webview shifts down, I guess you should revert the changes

**Comment by xdevs23** [comment] 2015-11-12 16:46
You have to pull down webview when  omnibox is visible, so it doesn't overlap.
And when omnibox disappears, just pull it up again.

And if the omnibox is at the bottom you have to pull it down although because the status bar is overlapping it. (Let me analyze the situation please and I will try to fix it)

**Comment by Thunderbottom** [comment] 2015-11-12 16:48
No, what I'm saying is if you pull it down twice, it comes back into view, but if you keep pulling, then the webview gets dragged along with it and a white padding appears above. 
I'm pretty sure some old commit broke it.... I'm checking it too

**Comment by xdevs23** [comment] 2015-11-12 16:49
Yes, I know, I have seen that, just a few if statements would fix that, too.
But it is a step into the right direction.

**Comment by xdevs23** [comment] 2015-11-12 17:16
Great news: It is almost finished

**Comment by Thunderbottom** [comment] 2015-11-12 17:17
:+1:

**Comment by xdevs23** [comment] 2015-11-12 18:15
Didn't finish today, but will do later.

Please tell me if you solved it yourself in the meantime.

I need to know what changes the height and what changes the 'top offset' in your code...

It is working but somehow immediately after the webview is positioned correctly, it restores the previous **wrong** position.

Tell me where you did something like "view.layout()" on the webview.

Thanks

**Comment by Thunderbottom** [comment] 2015-11-13 03:43
[This](https://github.com/balzathor/UltimateBrowserProject/blob/83f21a387e1b4b5243edd0eadcbaba17c2434e9c/app/src/main/java/io/github/UltimateBrowserProject/Unit/ViewUnit.java#L48v) and [this](https://github.com/balzathor/UltimateBrowserProject/blob/83f21a387e1b4b5243edd0eadcbaba17c2434e9c/app/src/main/java/io/github/UltimateBrowserProject/View/UltimateBrowserProjectWebView.java#L162) is where I think the problem might be..

**Comment by Thunderbottom** [comment] 2015-11-13 03:45
@james9909 any idea on where this might be?

**Comment by james9909** [comment] 2015-11-13 03:55
Unfortunately, I don't have enough time to look into the situation, and am very sorry about my unavailability for the past few months.

**Comment by Thunderbottom** [comment] 2015-11-13 05:37
Well, that's fine. I'll go through it myself :)

**Comment by xdevs23** [comment] 2015-11-13 06:38
What you've marked were my tries to get the webview under the omnibox when it shows up.

I have uncommented the part here but didn't come to commit it: https://github.com/balzathor/UltimateBrowserProject/blob/83f21a387e1b4b5243edd0eadcbaba17c2434e9c/app/src/main/java/io/github/UltimateBrowserProject/Unit/ViewUnit.java#L48v

I had success doing it, but it was buggy, I have to think more about it and do something better, but basically the fix/workaround I am doing works.

**Comment by xdevs23** [comment] 2015-11-13 06:42
Also you did not handle the navigation bar size.
For example, on my device, there is 50px of adjustHeight and 1200 of window height but the screen has 1280 height, so there's 30px missing...
And this could also be what is missing

**Comment by Thunderbottom** [comment] 2015-11-13 07:11
Can you explain the last part a bit more?

**Comment by xdevs23** [comment] 2015-11-13 13:08
[See here](https://github.com/balzathor/UltimateBrowserProject/blob/83f21a387e1b4b5243edd0eadcbaba17c2434e9c/app/src/main/java/io/github/UltimateBrowserProject/Unit/ViewUnit.java#L23v)

My screen resolution is 720x1280
Width is 720, Height is 1280
The window height is 1200, window width is 720, adjustHeight is 50, so status bar height is also 50.

1200 + 50 = 1250 but not 1280, so there are 30 pixels missing.

See here:

``` java
    public static boolean respectAdjustHeight = true;
    private static int adjustHeightMultiplier = 1;
    public static void bound(Context context, View view, boolean isFullScreen) {
        int windowWidth = getWindowWidth(context);    // gives 720, which is correct
        int windowHeight = getWindowHeight(context); // gives 1200
        int adjustHeight = 0;
        if (!isFullScreen && respectAdjustHeight)
            adjustHeight += getStatusBarHeight(context) * adjustHeightMultiplier;  // gives 50
      ...
```

The log here (from logcat):

```
Window height: 1200; Window width: 720; Adjust height: 50; status bar height: 50;widthSpec: 1073742544; heightSpec: 1073742974
```

is the result of

``` java
        Logging.logt(String.format(
                "Window height: %s; Window width: %s; "
              + "Adjust height: %s; status bar height: %s;"
              + "widthSpec: %s; heightSpec: %s",
                windowHeight, windowWidth,
                adjustHeight, getStatusBarHeight(context),
                widthSpec, heightSpec
        ));
```

The status bar has 50 pixels in height but the navbar has 80 pixels in height and not 30...
So where do the 30 belong to?

(Navbar - status bar = 30; 80 - 50 = 30, but I don't think that has anything to do with...)

We are not talking about dp (Density Pixels), these are real pixels....

See the screenshot:
![scr13](https://cloud.githubusercontent.com/assets/6959245/11146506/40798f0e-8a0f-11e5-97f1-717562d36c03.png)

**Comment by Thunderbottom** [comment] 2015-11-13 13:40
Alright I get what you're saying, but that isn't the problem I guess. The screen size is set to 1250x720 just because the status bar/navbar takes up 30px. And in fullscreen mode if you see, it is totally hidden, where it works fine. I think there's some thing wrong in WebView...

**Comment by xdevs23** [comment] 2015-11-13 13:44
Yes, check out [this](https://github.com/balzathor/UltimateBrowserProject/pull/43).
There is something missing, I guess.

**Comment by xdevs23** [comment] 2015-11-13 13:45
The problem is basically that the webview has to be pulln down when omnibox is visible, because it is overlaying the webview.

And with the bottom option, I think, the webview is under the status bar. You simply have to pull down the webview 96px (what is the height of the omnibox?) when it is shown. Doesn't matter if top or bottom, just do it and it works.

**Comment by Thunderbottom** [comment] 2015-11-13 13:55
You were working on some fix right? how is it going?

**Comment by xdevs23** [comment] 2015-11-13 13:59
Well, it seems to work but the webview restores the previous position.

I have to look what is blocking

Don't know...

**Comment by xdevs23** [comment] 2015-11-13 14:10
Look here, I have this code now:

``` java
    @Override
    public void hideOmnibox(View view) {
        if (omnibox.getVisibility() != View.GONE) {
            Animation hide;
            if (anchor == 0) {
                if (contentFrame.findViewById(R.id.main_omnibox) == null) {
                    ((ViewGroup)omnibox.getParent()).removeView(omnibox);
                    contentFrame.addView(omnibox);
                    omnibox.bringToFront();
                }
                hide = AnimationUtils.loadAnimation(getApplicationContext(), R.anim.slide_top_up);


                int     l = view.getLeft(),
                        t = view.getTop(),
                        b = view.getBottom(),
                        r = view.getRight(),

                        sbOffset = getResources().getDimensionPixelSize(getResources()
                                .getIdentifier("status_bar_height", "dimen", "android")),

                        nbOffset = getResources().getDimensionPixelSize(getResources()
                                .getIdentifier("navigation_bar_height", "dimen", "android"))

                                ;
                view.layout(
                        l,
                        t - 96,
                        r,
                        b
                );
            } else {
                return;
            }
            hide.setAnimationListener(new Animation.AnimationListener() {

                @Override
                public void onAnimationStart(Animation animation) {}

                @Override
                public void onAnimationEnd(Animation animation) {
                    omnibox.setVisibility(View.GONE);
                    setBound((View) currentAlbumController);
                }

                @Override
                public void onAnimationRepeat(Animation animation) {}
            });
            omnibox.startAnimation(hide);
        }
    }

    @Override
    public void showOmnibox(View view) {
        if (omnibox.getVisibility() != View.VISIBLE) {
            Animation show;
            if (anchor == 0) {
                if (contentFrame.findViewById(R.id.main_omnibox) == null) {
                    ((ViewGroup)omnibox.getParent()).removeView(omnibox);
                    contentFrame.addView(omnibox);
                    omnibox.bringToFront();
                }
                show = AnimationUtils.loadAnimation(getApplicationContext(), R.anim.slide_top_down);
            } else {
                return;
            }

            show.setAnimationListener(new Animation.AnimationListener() {

                @Override
                public void onAnimationStart(Animation animation) {
                }

                @Override
                public void onAnimationEnd(Animation animation) {
                    omnibox.setVisibility(View.VISIBLE);
                    setBound((View) currentAlbumController);
                }

                @Override
                public void onAnimationRepeat(Animation animation) {
                }
            });

            omnibox.startAnimation(show);


            int     l = view.getLeft(),
                    t = view.getTop(),
                    b = view.getBottom(),
                    r = view.getRight(),

                    sbOffset = getResources().getDimensionPixelSize(getResources()
                            .getIdentifier("status_bar_height", "dimen", "android")),

                    nbOffset = getResources().getDimensionPixelSize(getResources()
                            .getIdentifier("navigation_bar_height", "dimen", "android"))

                            ;


            view.layout(
                    l,
                    t + 96,
                    r,
                    b
            );
        }
    }
```

In this (50% slower) video you can see that it gets pulln down but when the omnibox appears, it goes up again.
![ezgif-4267518258](https://cloud.githubusercontent.com/assets/6959245/11147768/9329dff2-8a18-11e5-828d-6ad71bd51dfd.gif)

**EDIT:**
You can see that the webview is behind the omnibox **by swiping the omnibox to the right and holding it**

**Comment by xdevs23** [comment] 2015-11-13 15:30
Ok, so now I am getting it fixed, the code is just wasted up and many things are blocking other things...
I am finishing.
For now it is working very good, just have to finish, and I hope it works...

**Comment by xdevs23** [comment] 2015-11-13 15:31
Sorry, I accidentally clicked on Close and comment

**Comment by xdevs23** [comment] 2015-11-13 16:03
It is working!

But without animation, I think we could add that later...
Will commit now

**Comment by Thunderbottom** [comment] 2015-11-13 16:06
I've seen that thing happen before, not sure where...

**Comment by Thunderbottom** [comment] 2015-11-13 16:07
Sorry, I would've fixed this myself but I have exams coming up in 5 days so I can't do much at this moment. Thanks for helping though :)

**Comment by xdevs23** [comment] 2015-11-13 16:11
I already fixed it...
I just wrote some things from scratch, and used my own ideas for it, now it works perfectly fine, just the slide in/out animation is missing but that we can do later.

Nothing is cropped at the top:
![scrw1](https://cloud.githubusercontent.com/assets/6959245/11150645/4bb9f2d6-8a29-11e5-9f9b-d3b1e9510f64.png)

Nothing is cropped at the top:
![scrw2](https://cloud.githubusercontent.com/assets/6959245/11150646/4bbcece8-8a29-11e5-98fa-0635e64d2815.png)

And when using omnibox at the top, it is not overlaying:
![scrw3](https://cloud.githubusercontent.com/assets/6959245/11150647/4bbeeeda-8a29-11e5-8fd3-85a2978a2c04.png)

**Comment by Thunderbottom** [comment] 2015-11-13 16:14
That's awesome, although the animation was very much needed there..

**Comment by Thunderbottom** [comment] 2015-11-13 16:17
Well, I'll just remove the "Hide omnibox" for now, I'm facing some glitches..

**Comment by xdevs23** [comment] 2015-11-13 16:24
Well, I have a better idea for an animation, but I'm glad that the bug is at least fixed, so we could just leave it how it is now and I will make the animation, I am sure that it will be awesome :smiley:

**Comment by Thunderbottom** [comment] 2015-11-13 16:27
Can you try to reproduce the glitch so that I can make sure it's not happening only for me?

**Comment by Thunderbottom** [comment] 2015-11-13 16:28
Try to load a page and hide the omnibox, then try to bring up the omnibox again, the omnibox shifts to the center of the display for a second or so and then comes back to normal.

**Comment by xdevs23** [comment] 2015-11-13 16:41
No, I don't have this glitch, it is working perfectly fine on my device...

**Comment by Thunderbottom** [comment] 2015-11-13 17:07
Can you do this while the page is loading?

**Comment by xdevs23** [comment] 2015-11-13 17:14
Oh I see, that is not a glitch, it has something to do with the layout, we have to set a fixed size for the omnibox, because while the webview is loading a page, the omnibox just stretches up to the whole height.
But that's not hard to do...

**Comment by xdevs23** [comment] 2015-11-13 17:27
Fixing it and creating an animation...

**Comment by xdevs23** [comment] 2015-11-13 19:31
@balzathor would be nice if you let me do the job, so the omnibox is working correctly with the webview

**Comment by Thunderbottom** [comment] 2015-11-14 03:27
As I said, do anything just don't break it lol

**Comment by xdevs23** [comment] 2015-11-14 08:18
Ok, will do the work

**Comment by xdevs23** [comment] 2015-11-14 12:18
@balzathor It's fixed now :D

Maybe there's a tiny lag but that is a minor thing which we can ignore for now and fix it later.

**Comment by Thunderbottom** [comment] 2015-11-14 16:17
Check this out - 
![checkthisout](https://cloud.githubusercontent.com/assets/11243138/11164500/974b101e-8b18-11e5-8f76-6b36a1570f94.gif)

**Comment by Thunderbottom** [comment] 2015-11-14 16:20
The gif is slow, but if you can test it, you'll see that the omnibox has a glitch when it appears, slowly pulling the WebView down with it for a split second, then getting back to normal. Also, sometimes when you swipe it up and down pretty fast, the omnibox appears before it actually should

**Comment by xdevs23** [comment] 2015-11-14 16:23
Yes because the webview is a bit slower than the omnibox, but that shouldn't be a problem, also the glitch that it appears quickly when starting pulling the webview down is a tiny logical thing which isn't yet implemented in the code.

**Comment by xdevs23** [comment] 2015-11-14 16:24
Sorry accidentally clicked on wrong button

**Closed as completed by xdevs23** 2015-11-14 16:23 UTC

**Comment by xdevs23** [comment] 2015-11-14 16:45
@balzathor It's fixed now :D
